version: "3.5"

services:
  backend:
    build:
      context: ./cod
      dockerfile: src/main/docker/Dockerfile.jvm
    ports:
      - "8080:8080"
    volumes:
      - ./build/quarkus-app:/deployments
    environment:
      - JAVA_OPTS_APPEND=-Dquarkus.http.host=0.0.0.0 -Djava.util.logging.manager=org.jboss.logmanager.LogManager

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
